In [1]:
import numpy as np
import pandas as pd
import collaborative_filtering
cf = collaborative_filtering.collaborative_filtering(r"C:\Users\SHIVAM MAHAJAN\Desktop\Github\Recommendation-System\Data\Demo Data.xlsm")

In [2]:
cf.utility_matrix

array([[ 1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  0.,  0.],
       [ 0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  1.,  1.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  1.,  0.,  1.,  1.,  1.,  0.,  0.,  0.],
       [ 1.,  0.,  1.,  0.,  1.,  1.,  1.,  0.,  0.,  0.],
       [ 0.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  0.],
       [ 0.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  0.],
       [ 0.,  0.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.],
       [ 0.,  0.,  1.,  1.,  1.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  0.],
       [ 1.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  0.],
       [ 1.,  1.,  1.,  1.,  0.,  0.,  1.,  0.,  1.,  1.],
       [ 0.,  1.,  0.,  1.,  1.,  0.,  1.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  1.,  1.,  0.,  1.,  0.,  0.,  0.

In [3]:
cf.similarity_mat()

array([[ 1.        ,  0.55603844,  0.46156633,  0.50083542,  0.46156633,
         0.50738257,  0.62869461,  0.50738257,  0.42911912,  0.44982345],
       [ 0.55603844,  1.        ,  0.65880785,  0.69388867,  0.60610322,
         0.59481188,  0.67840053,  0.64888568,  0.54307885,  0.45760432],
       [ 0.46156633,  0.65880785,  1.        ,  0.73423604,  0.725     ,
         0.58993755,  0.66742381,  0.69253539,  0.62367507,  0.58916499],
       [ 0.50083542,  0.69388867,  0.73423604,  1.        ,  0.6329621 ,
         0.70135785,  0.72420682,  0.72733407,  0.65908204,  0.56526686],
       [ 0.46156633,  0.60610322,  0.725     ,  0.6329621 ,  1.        ,
         0.61558701,  0.73893351,  0.71818485,  0.67790768,  0.52714762],
       [ 0.50738257,  0.59481188,  0.58993755,  0.70135785,  0.61558701,
         1.        ,  0.73367398,  0.65789474,  0.66769786,  0.47721357],
       [ 0.62869461,  0.67840053,  0.66742381,  0.72420682,  0.73893351,
         0.73367398,  1.        ,  0.73367398

In [4]:
cf.similarity_matrix

array([[ 1.        ,  0.55603844,  0.46156633,  0.50083542,  0.46156633,
         0.50738257,  0.62869461,  0.50738257,  0.42911912,  0.44982345],
       [ 0.55603844,  1.        ,  0.65880785,  0.69388867,  0.60610322,
         0.59481188,  0.67840053,  0.64888568,  0.54307885,  0.45760432],
       [ 0.46156633,  0.65880785,  1.        ,  0.73423604,  0.725     ,
         0.58993755,  0.66742381,  0.69253539,  0.62367507,  0.58916499],
       [ 0.50083542,  0.69388867,  0.73423604,  1.        ,  0.6329621 ,
         0.70135785,  0.72420682,  0.72733407,  0.65908204,  0.56526686],
       [ 0.46156633,  0.60610322,  0.725     ,  0.6329621 ,  1.        ,
         0.61558701,  0.73893351,  0.71818485,  0.67790768,  0.52714762],
       [ 0.50738257,  0.59481188,  0.58993755,  0.70135785,  0.61558701,
         1.        ,  0.73367398,  0.65789474,  0.66769786,  0.47721357],
       [ 0.62869461,  0.67840053,  0.66742381,  0.72420682,  0.73893351,
         0.73367398,  1.        ,  0.73367398

In [5]:
cf.final_recommendation_score_matrix()

array([[ 4.12263085,  4.74304759,  4.79527093,  4.71482098,  4.86537491,
         4.69928773,  5.18080042,  4.95855721,  4.22574895,  3.69223963],
       [ 4.16189994,  4.83083304,  4.80450697,  5.08185887,  4.49833702,
         4.78505857,  5.16607374,  4.96770643,  4.20692332,  3.73035888],
       [ 1.98000652,  2.95879973,  3.11804389,  3.06108681,  2.96406532,
         2.50169429,  2.80896467,  2.78693999,  2.50374364,  2.13918379],
       [ 2.02582276,  2.94750839,  2.98298144,  3.12948256,  2.57965233,
         2.88610728,  2.80370514,  2.72664988,  2.49353382,  2.08924974],
       [ 2.61524828,  3.53812347,  3.64116921,  3.48665149,  3.68562374,
         3.53401042,  3.81843183,  3.45117464,  3.18457346,  2.70157413],
       [ 3.05920984,  3.0941619 ,  3.4439277 ,  3.29359824,  3.54108685,
         3.44658111,  3.76872591,  3.30967152,  3.07061373,  2.69379327],
       [ 1.44672389,  2.2018867 ,  2.28248291,  2.08720675,  2.0090109 ,
         1.85244729,  2.01803833,  1.95347744

In [6]:
cf.output_recommendations()

Customer_id  Merchant_id  Recommended_score  Rank  Flag
0            1.0          7.0           5.180800   1.0   1.0
1            1.0          8.0           4.958557   2.0   1.0
2            1.0          5.0           4.865375   3.0   1.0
3            1.0          3.0           4.795271   4.0   1.0
4            1.0          2.0           4.743048   5.0   1.0
5            1.0          4.0           4.714821   6.0   0.0
6            1.0          6.0           4.699288   7.0   1.0
7            1.0          9.0           4.225749   8.0   0.0
8            1.0          1.0           4.122631   9.0   1.0
9            1.0         10.0           3.692240  10.0   0.0
10           2.0          7.0           5.166074   1.0   1.0
11           2.0          4.0           5.081859   2.0   1.0
12           2.0          8.0           4.967706   3.0   1.0
13           2.0          2.0           4.830833   4.0   1.0
14           2.0          3.0           4.804507   5.0   1.0
15           2.0          6.0           4.785059   6.0   1.0
16           2.0          5.0           4.498337   7.0   0.0
17           2.0          9.0           4.206923   8.0   0.0
18           2.0          1.0           4.161900   9.0   1.0
19           2.0         10.0           3.730359  10.0   0.0
20           3.0          3.0           3.118044   1.0   1.0
21           3.0          4.0           3.061087   2.0   1.0
22           3.0          5.0           2.964065   3.0   1.0
23           3.0          2.0           2.958800   4.0   1.0
24           3.0          7.0           2.808965   5.0   0.0
25           3.0          8.0           2.786940   6.0   0.0
26           3.0          9.0           2.503744   7.0   0.0
27           3.0          6.0           2.501694   8.0   0.0
28           3.0         10.0           2.139184   9.0   0.0
29           3.0          1.0           1.980007  10.0   0.0
..           ...          ...                ...   ...   ...
540         55.0          3.0           4.127075   1.0   1.0
541         55.0          8.0           4.107831   2.0   1.0
542         55.0          7.0           4.097570   3.0   0.0
543         55.0          5.0           4.038002   4.0   1.0
544         55.0          2.0           3.927440   5.0   1.0
545         55.0          4.0           3.854523   6.0   0.0
546         55.0         10.0           3.564582   7.0   1.0
547         55.0          9.0           3.491243   8.0   0.0
548         55.0          6.0           3.442827   9.0   0.0
549         55.0          1.0           3.436377  10.0   1.0
550         56.0          7.0           5.825058   1.0   1.0
551         56.0          5.0           5.464327   2.0   1.0
552         56.0          8.0           5.462570   3.0   1.0
553         56.0          3.0           5.349303   4.0   1.0
554         56.0          9.0           5.288076   5.0   1.0
555         56.0          6.0           5.249387   6.0   1.0
556         56.0          4.0           5.245281   7.0   0.0
557         56.0         10.0           4.840041   8.0   1.0
558         56.0          2.0           4.743731   9.0   0.0
559         56.0          1.0           4.445535  10.0   1.0
560         57.0          7.0           4.608889   1.0   1.0
561         57.0          8.0           4.485973   2.0   1.0
562         57.0          4.0           4.479750   3.0   1.0
563         57.0          5.0           4.311771   4.0   1.0
564         57.0          6.0           4.303325   5.0   1.0
565         57.0          2.0           4.222090   6.0   1.0
566         57.0          3.0           4.067941   7.0   0.0
567         57.0          9.0           3.832037   8.0   0.0
568         57.0         10.0           3.218518   9.0   0.0
569         57.0          1.0           3.161900  10.0   0.0

[570 rows x 5 columns]

In [8]:
cf2 = collaborative_filtering.collaborative_filtering(r"C:\Users\SHIVAM MAHAJAN\Desktop\Github\Recommendation-System\Data\Demo Data.xlsm"\
                                                      ,type = "item",product = "jac" )

In [9]:
cf2.utility_matrix

array([[ 1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  0.,  0.],
       [ 0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  1.,  1.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  1.,  0.,  1.,  1.,  1.,  0.,  0.,  0.],
       [ 1.,  0.,  1.,  0.,  1.,  1.,  1.,  0.,  0.,  0.],
       [ 0.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  0.],
       [ 0.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  0.],
       [ 0.,  0.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.],
       [ 0.,  0.,  1.,  1.,  1.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  0.],
       [ 1.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  0.],
       [ 1.,  1.,  1.,  1.,  0.,  0.,  1.,  0.,  1.,  1.],
       [ 0.,  1.,  0.,  1.,  1.,  0.,  1.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  1.,  1.,  0.,  1.,  0.,  0.,  0.

In [10]:
cf2.similarity_mat()

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

In [11]:
cf2.final_recommendation_score_matrix()

array([[ 1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  0.,  0.],
       [ 0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  1.,  1.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  1.,  0.,  1.,  1.,  1.,  0.,  0.,  0.],
       [ 1.,  0.,  1.,  0.,  1.,  1.,  1.,  0.,  0.,  0.],
       [ 0.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  0.],
       [ 0.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  0.],
       [ 0.,  0.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.],
       [ 0.,  0.,  1.,  1.,  1.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  0.],
       [ 1.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  0.],
       [ 1.,  1.,  1.,  1.,  0.,  0.,  1.,  0.,  1.,  1.],
       [ 0.,  1.,  0.,  1.,  1.,  0.,  1.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  1.,  1.,  0.,  1.,  0.,  0.,  0.

In [12]:
cf2.output_recommendations()

Customer_id  Merchant_id  Recommended_score  Rank  Flag
0            1.0          1.0                1.0   1.0   1.0
1            1.0          2.0                1.0   1.0   1.0
2            1.0          3.0                1.0   1.0   1.0
3            1.0          5.0                1.0   1.0   1.0
4            1.0          6.0                1.0   1.0   1.0
5            1.0          7.0                1.0   1.0   1.0
6            1.0          8.0                1.0   1.0   1.0
7            1.0          4.0                0.0  10.0   0.0
8            1.0          9.0                0.0  10.0   0.0
9            1.0         10.0                0.0  10.0   0.0
10           2.0          1.0                1.0   1.0   1.0
11           2.0          2.0                1.0   1.0   1.0
12           2.0          3.0                1.0   1.0   1.0
13           2.0          4.0                1.0   1.0   1.0
14           2.0          6.0                1.0   1.0   1.0
15           2.0          7.0                1.0   1.0   1.0
16           2.0          8.0                1.0   1.0   1.0
17           2.0          5.0                0.0  10.0   0.0
18           2.0          9.0                0.0  10.0   0.0
19           2.0         10.0                0.0  10.0   0.0
20           3.0          2.0                1.0   1.0   1.0
21           3.0          3.0                1.0   1.0   1.0
22           3.0          4.0                1.0   1.0   1.0
23           3.0          5.0                1.0   1.0   1.0
24           3.0          1.0                0.0  10.0   0.0
25           3.0          6.0                0.0  10.0   0.0
26           3.0          7.0                0.0  10.0   0.0
27           3.0          8.0                0.0  10.0   0.0
28           3.0          9.0                0.0  10.0   0.0
29           3.0         10.0                0.0  10.0   0.0
..           ...          ...                ...   ...   ...
540         55.0          1.0                1.0   1.0   1.0
541         55.0          2.0                1.0   1.0   1.0
542         55.0          3.0                1.0   1.0   1.0
543         55.0          5.0                1.0   1.0   1.0
544         55.0          8.0                1.0   1.0   1.0
545         55.0         10.0                1.0   1.0   1.0
546         55.0          4.0                0.0  10.0   0.0
547         55.0          6.0                0.0  10.0   0.0
548         55.0          7.0                0.0  10.0   0.0
549         55.0          9.0                0.0  10.0   0.0
550         56.0          1.0                1.0   1.0   1.0
551         56.0          3.0                1.0   1.0   1.0
552         56.0          5.0                1.0   1.0   1.0
553         56.0          6.0                1.0   1.0   1.0
554         56.0          7.0                1.0   1.0   1.0
555         56.0          8.0                1.0   1.0   1.0
556         56.0          9.0                1.0   1.0   1.0
557         56.0         10.0                1.0   1.0   1.0
558         56.0          2.0                0.0  10.0   0.0
559         56.0          4.0                0.0  10.0   0.0
560         57.0          2.0                1.0   1.0   1.0
561         57.0          4.0                1.0   1.0   1.0
562         57.0          5.0                1.0   1.0   1.0
563         57.0          6.0                1.0   1.0   1.0
564         57.0          7.0                1.0   1.0   1.0
565         57.0          8.0                1.0   1.0   1.0
566         57.0          1.0                0.0  10.0   0.0
567         57.0          3.0                0.0  10.0   0.0
568         57.0          9.0                0.0  10.0   0.0
569         57.0         10.0                0.0  10.0   0.0

[570 rows x 5 columns]

In [14]:
cf3 = collaborative_filtering.collaborative_filtering(r"C:\Users\SHIVAM MAHAJAN\Desktop\Github\Recommendation-System\Data\Demo Data.xlsm", \
                                                      type = "user")

In [15]:
cf3.similarity_mat()

array([[ 1.        ,  0.85714286,  0.56694671, ...,  0.77151675,
         0.80178373,  0.77151675],
       [ 0.85714286,  1.        ,  0.56694671, ...,  0.6172134 ,
         0.6681531 ,  0.77151675],
       [ 0.56694671,  0.56694671,  1.        , ...,  0.61237244,
         0.35355339,  0.61237244],
       ..., 
       [ 0.77151675,  0.6172134 ,  0.61237244, ...,  1.        ,
         0.72168784,  0.5       ],
       [ 0.80178373,  0.6681531 ,  0.35355339, ...,  0.72168784,
         1.        ,  0.57735027],
       [ 0.77151675,  0.77151675,  0.61237244, ...,  0.5       ,
         0.57735027,  1.        ]])

In [16]:
cf3.similarity_matrix

array([[ 1.        ,  0.85714286,  0.56694671, ...,  0.77151675,
         0.80178373,  0.77151675],
       [ 0.85714286,  1.        ,  0.56694671, ...,  0.6172134 ,
         0.6681531 ,  0.77151675],
       [ 0.56694671,  0.56694671,  1.        , ...,  0.61237244,
         0.35355339,  0.61237244],
       ..., 
       [ 0.77151675,  0.6172134 ,  0.61237244, ...,  1.        ,
         0.72168784,  0.5       ],
       [ 0.80178373,  0.6681531 ,  0.35355339, ...,  0.72168784,
         1.        ,  0.57735027],
       [ 0.77151675,  0.77151675,  0.61237244, ...,  0.5       ,
         0.57735027,  1.        ]])

In [17]:
cf3.output_recommendations()

Customer_id  Merchant_id  Recommended_score  Rank  Flag
0            1.0          7.0          31.058803   1.0   1.0
1            1.0          5.0          28.256012   2.0   1.0
2            1.0          3.0          27.738613   3.0   1.0
3            1.0          8.0          27.382773   4.0   1.0
4            1.0          6.0          26.382494   5.0   1.0
5            1.0          4.0          26.248763   6.0   0.0
6            1.0          2.0          25.750873   7.0   1.0
7            1.0          9.0          21.918948   8.0   0.0
8            1.0          1.0          17.053449   9.0   1.0
9            1.0         10.0          16.635354  10.0   0.0
10           2.0          7.0          30.785798   1.0   1.0
11           2.0          4.0          28.393020   2.0   1.0
12           2.0          3.0          27.695492   3.0   1.0
13           2.0          8.0          27.319701   4.0   1.0
14           2.0          6.0          26.715476   5.0   1.0
15           2.0          2.0          26.153270   6.0   1.0
16           2.0          5.0          25.778117   7.0   0.0
17           2.0          9.0          21.640939   8.0   0.0
18           2.0          1.0          17.167913   9.0   1.0
19           2.0         10.0          16.761263  10.0   0.0
20           3.0          3.0          24.479248   1.0   1.0
21           3.0          4.0          23.149219   2.0   1.0
22           3.0          5.0          23.115301   3.0   1.0
23           3.0          7.0          22.529319   4.0   0.0
24           3.0          2.0          21.830461   5.0   1.0
25           3.0          8.0          20.717999   6.0   0.0
26           3.0          6.0          18.868542   7.0   0.0
27           3.0          9.0          17.409103   8.0   0.0
28           3.0         10.0          12.913860   9.0   0.0
29           3.0          1.0          11.322108  10.0   0.0
..           ...          ...                ...   ...   ...
540         55.0          7.0          25.052483   1.0   0.0
541         55.0          3.0          24.770738   2.0   1.0
542         55.0          5.0          24.247056   3.0   1.0
543         55.0          8.0          23.576791   4.0   1.0
544         55.0          2.0          22.222056   5.0   1.0
545         55.0          4.0          22.150194   6.0   0.0
546         55.0          6.0          19.762545   7.0   0.0
547         55.0          9.0          18.531902   8.0   0.0
548         55.0         10.0          16.235435   9.0   1.0
549         55.0          1.0          14.628400  10.0   1.0
550         56.0          7.0          31.883659   1.0   1.0
551         56.0          5.0          28.960484   2.0   1.0
552         56.0          3.0          28.063162   3.0   1.0
553         56.0          8.0          27.525845   4.0   1.0
554         56.0          6.0          27.034229   5.0   1.0
555         56.0          4.0          26.564191   6.0   0.0
556         56.0          9.0          25.125440   7.0   1.0
557         56.0          2.0          23.436650   8.0   0.0
558         56.0         10.0          19.635444   9.0   1.0
559         56.0          1.0          16.836087  10.0   1.0
560         57.0          7.0          30.643579   1.0   1.0
561         57.0          4.0          27.624962   2.0   1.0
562         57.0          5.0          27.554034   3.0   1.0
563         57.0          8.0          27.343523   4.0   1.0
564         57.0          6.0          26.734048   5.0   1.0
565         57.0          3.0          25.824838   6.0   0.0
566         57.0          2.0          25.312872   7.0   1.0
567         57.0          9.0          21.917428   8.0   0.0
568         57.0         10.0          16.082278   9.0   0.0
569         57.0          1.0          14.893579  10.0   0.0

[570 rows x 5 columns]

In [18]:
cf3.similarity_matrix

array([[ 1.        ,  0.85714286,  0.56694671, ...,  0.77151675,
         0.80178373,  0.77151675],
       [ 0.85714286,  1.        ,  0.56694671, ...,  0.6172134 ,
         0.6681531 ,  0.77151675],
       [ 0.56694671,  0.56694671,  1.        , ...,  0.61237244,
         0.35355339,  0.61237244],
       ..., 
       [ 0.77151675,  0.6172134 ,  0.61237244, ...,  1.        ,
         0.72168784,  0.5       ],
       [ 0.80178373,  0.6681531 ,  0.35355339, ...,  0.72168784,
         1.        ,  0.57735027],
       [ 0.77151675,  0.77151675,  0.61237244, ...,  0.5       ,
         0.57735027,  1.        ]])

In [19]:
a = [4,6,2,1,3]
a[-4:]

[6, 2, 1, 3]

In [18]:
a = np.array([9, 4, 4, 3, 3, 9, 0, 4, 6, 0])
ind = np.argpartition(a, -4)[-4:]
ind

array([1, 5, 8, 0], dtype=int64)

In [19]:
a[ind]

array([4, 9, 6, 9])

In [20]:
a.sort()

In [21]:
a

array([0, 0, 3, 3, 4, 4, 4, 6, 9, 9])

In [22]:
cf3.similarity_matrix

array([[ 1.        ,  0.85714286,  0.56694671, ...,  0.77151675,
         0.80178373,  0.77151675],
       [ 0.85714286,  1.        ,  0.56694671, ...,  0.6172134 ,
         0.6681531 ,  0.77151675],
       [ 0.56694671,  0.56694671,  1.        , ...,  0.61237244,
         0.35355339,  0.61237244],
       ..., 
       [ 0.77151675,  0.6172134 ,  0.61237244, ...,  1.        ,
         0.72168784,  0.5       ],
       [ 0.80178373,  0.6681531 ,  0.35355339, ...,  0.72168784,
         1.        ,  0.57735027],
       [ 0.77151675,  0.77151675,  0.61237244, ...,  0.5       ,
         0.57735027,  1.        ]])

In [23]:
k = 10
value_user_matrix = np.zeros((k,cf3.similarity_matrix.shape[1]))
index_user_matrix = np.zeros((k,cf3.similarity_matrix.shape[1]))
for i in range(cf3.similarity_matrix.shape[1]):
    temp = cf3.similarity_matrix[:,i]
    ind = np.argpartition(temp, -k)[-k:]
    index_user_matrix[:,i] = ind
    value_user_matrix[:,i] = temp[ind]

In [24]:
index_user_matrix

array([[ 55.,  29.,  30.,   1.,  51.,  46.,  44.,   0.,   9.,  19.,  11.,
         47.,  25.,  42.,  52.,  50.,   1.,  47.,  52.,  21.,   9.,  20.,
         36.,  14.,   9.,   0.,  55.,  21.,  55.,  42.,  35.,  44.,  24.,
         39.,  56.,   8.,  29.,   5.,  25.,  55.,  20.,  34.,   7.,  53.,
         31.,  41.,  53.,  23.,  23.,   1.,  23.,  20.,  44.,  39.,  30.,
         39.,  35.],
       [ 53.,  49.,  44.,  35.,  56.,  37.,  48.,  35.,  35.,   4.,  28.,
         19.,  26.,  25.,  23.,  10.,   7.,  48.,  41.,  48.,  28.,  14.,
         41.,  10.,  56.,  35.,  12.,  52.,  47.,  25.,   0.,  19.,  25.,
         48.,  41.,   9.,  18.,  27.,  55.,  47.,  31.,  18.,  13.,  19.,
         30.,  13.,  44.,  33.,  33.,   8.,  55.,  35.,  41.,  10.,  47.,
         10.,  25.],
       [ 30.,  30.,   3.,  43.,  46.,  25.,  49.,  42.,  20.,   8.,  39.,
         30.,  51.,   1.,  21.,  23.,  37.,  35.,  36.,  55.,  39.,  10.,
         29.,  49.,   3.,  49.,   9.,  33.,  10.,   1.,  13.,  48.,  4

In [25]:
value_user_matrix
print(value_user_matrix.shape)

(10, 57)


In [26]:
#k_similar_users_profiles = np.zeros((k,cf3.utility_matrix.shape[1]))
#k_similar_users_similarity_values = np.zeros(k)
final_user_item_score = np.zeros(cf3.utility_matrix.shape)
for i in range(index_user_matrix.shape[1]):
    temp = index_user_matrix[:,i].astype(int)
    k_similar_users_profiles = cf3.utility_matrix[temp]
    k_similar_users_similarity_values = value_user_matrix[:,i]
    final_user_item_score[i,:] = np.dot(k_similar_users_similarity_values,k_similar_users_profiles)

In [27]:
final_user_item_score.shape

(57, 10)

In [20]:
cf4 = collaborative_filtering.collaborative_filtering(r"C:\Users\SHIVAM MAHAJAN\Desktop\Github\Recommendation-System\Data\Demo Data.xlsm",\
                                                      type = "user",algo = "knn")

In [21]:
cf4.similarity_mat()

array([[ 1.        ,  0.85714286,  0.56694671, ...,  0.77151675,
         0.80178373,  0.77151675],
       [ 0.85714286,  1.        ,  0.56694671, ...,  0.6172134 ,
         0.6681531 ,  0.77151675],
       [ 0.56694671,  0.56694671,  1.        , ...,  0.61237244,
         0.35355339,  0.61237244],
       ..., 
       [ 0.77151675,  0.6172134 ,  0.61237244, ...,  1.        ,
         0.72168784,  0.5       ],
       [ 0.80178373,  0.6681531 ,  0.35355339, ...,  0.72168784,
         1.        ,  0.57735027],
       [ 0.77151675,  0.77151675,  0.61237244, ...,  0.5       ,
         0.57735027,  1.        ]])

In [22]:
cf4.output_recommendations()

Customer_id  Merchant_id  Recommended_score  Rank  Flag
0            1.0          7.0           8.326812   1.0   1.0
1            1.0          5.0           7.469669   2.0   1.0
2            1.0          3.0           6.679874   3.0   1.0
3            1.0          6.0           6.679874   3.0   1.0
4            1.0          1.0           6.636503   5.0   1.0
5            1.0          8.0           6.636503   5.0   1.0
6            1.0          2.0           5.032936   7.0   1.0
7            1.0          4.0           4.144411   8.0   0.0
8            1.0          9.0           3.287268   9.0   0.0
9            1.0         10.0           1.603567  10.0   0.0
10           2.0          2.0           8.486814   1.0   1.0
11           2.0          6.0           7.685030   2.0   1.0
12           2.0          8.0           7.641660   3.0   1.0
13           2.0          7.0           7.629671   4.0   1.0
14           2.0          4.0           7.629671   5.0   1.0
15           2.0          3.0           6.038092   6.0   1.0
16           2.0          1.0           5.846708   7.0   1.0
17           2.0          9.0           5.001554   8.0   0.0
18           2.0          5.0           4.144411   9.0   0.0
19           2.0         10.0           0.857143  10.0   0.0
20           3.0          2.0           7.461533   1.0   1.0
21           3.0          3.0           7.461533   1.0   1.0
22           3.0          4.0           6.711533   3.0   1.0
23           3.0          5.0           6.711533   3.0   1.0
24           3.0          9.0           4.389107   5.0   0.0
25           3.0          6.0           3.773716   6.0   0.0
26           3.0          8.0           3.736639   7.0   0.0
27           3.0          7.0           3.633178   8.0   0.0
28           3.0         10.0           3.633178   9.0   0.0
29           3.0          1.0           1.523603  10.0   0.0
..           ...          ...                ...   ...   ...
540         55.0          5.0           7.531599   1.0   1.0
541         55.0          2.0           6.809912   3.0   1.0
542         55.0          8.0           6.809912   3.0   1.0
543         55.0          3.0           6.801303   4.0   1.0
544         55.0          7.0           5.881769   5.0   0.0
545         55.0          1.0           4.500210   6.0   1.0
546         55.0          4.0           4.441773   7.0   0.0
547         55.0          9.0           3.658268   8.0   0.0
548         55.0         10.0           3.658268   8.0   1.0
549         55.0          6.0           1.493205  10.0   0.0
550         56.0          3.0           7.514144   1.0   1.0
551         56.0          5.0           7.514144   1.0   1.0
552         56.0          8.0           7.449902   3.0   1.0
553         56.0          9.0           7.440927   4.0   1.0
554         56.0          7.0           6.712360   5.0   1.0
555         56.0         10.0           6.689186   6.0   1.0
556         56.0          4.0           6.583877   7.0   0.0
557         56.0          6.0           5.782093   8.0   1.0
558         56.0          1.0           3.367767   9.0   1.0
559         56.0          2.0           0.824958  10.0   0.0
560         57.0          8.0           8.350734   1.0   1.0
561         57.0          7.0           7.579218   2.0   1.0
562         57.0          6.0           7.517401   3.0   1.0
563         57.0          2.0           7.517401   5.0   1.0
564         57.0          4.0           7.517401   5.0   1.0
565         57.0          5.0           6.745884   6.0   1.0
566         57.0          9.0           6.684068   7.0   0.0
567         57.0          3.0           3.192863   8.0   0.0
568         57.0          1.0           2.548547   9.0   0.0
569         57.0         10.0           0.833333  10.0   0.0

[570 rows x 5 columns]

In [31]:
k = 5
value_item_matrix = np.zeros((k,cf2.similarity_matrix.shape[1]))
index_item_matrix = np.zeros((k,cf2.similarity_matrix.shape[0]))
for i in range(cf2.similarity_matrix.shape[1]):
    temp = cf2.similarity_matrix[:,i]
    ind = np.argpartition(temp, -k)[-k:]
    index_item_matrix[:,i] = ind
    value_item_matrix[:,i] = temp[ind] 

In [32]:
value_item_matrix

array([[ 0.32608696,  0.48      ,  0.5       ,  0.54      ,  0.51020408,
         0.49019608,  0.56603774,  0.52941176,  0.48979592,  0.38297872],
       [ 0.32608696,  0.49019608,  0.52941176,  0.56603774,  0.56      ,
         0.5       ,  0.57692308,  0.57692308,  0.5       ,  0.40425532],
       [ 0.37209302,  0.50943396,  0.56862745,  0.57142857,  0.56862745,
         0.54      ,  0.57692308,  1.        ,  0.5       ,  0.42857143],
       [ 0.42553191,  1.        ,  0.58      ,  1.        ,  0.58490566,
         0.57692308,  1.        ,  0.57142857,  1.        ,  0.45833333],
       [ 1.        ,  0.53061224,  1.        ,  0.58      ,  1.        ,
         1.        ,  0.58490566,  0.56      ,  0.51020408,  1.        ]])

In [33]:
index_item_matrix

array([[ 7.,  7.,  6.,  5.,  8.,  7.,  3.,  2.,  3.,  3.],
       [ 5.,  2.,  7.,  6.,  7.,  8.,  5.,  6.,  6.,  2.],
       [ 1.,  6.,  4.,  7.,  2.,  3.,  7.,  7.,  5.,  8.],
       [ 6.,  1.,  3.,  3.,  6.,  6.,  6.,  3.,  8.,  6.],
       [ 0.,  3.,  2.,  2.,  4.,  5.,  4.,  4.,  4.,  9.]])

In [34]:
#k_similar_users_profiles = np.zeros((k,cf3.utility_matrix.shape[1]))
#k_similar_users_similarity_values = np.zeros(k)
final_user_item_score = np.zeros(cf2.utility_matrix.shape)
for i in range(index_item_matrix.shape[1]):
    temp = index_item_matrix[:,i].astype(int)
    k_similar_item_profiles = cf2.utility_matrix.T[temp]
    k_similar_item_similarity_values = value_item_matrix[:,i]
    final_user_item_score[:,i] = np.dot(k_similar_item_similarity_values,k_similar_item_profiles)

In [35]:
final_user_item_score

array([[ 2.44979885,  2.47963004,  2.59803922,  2.25746631,  2.71353311,
         2.06711916,  2.73875181,  2.66633484,  1.51020408,  0.86258865],
       [ 2.44979885,  3.01024229,  2.60941176,  3.25746631,  1.71353311,
         2.60711916,  2.71988389,  2.67776341,  1.48979592,  1.24556738],
       [ 0.37209302,  2.02080832,  2.14862745,  1.58      ,  1.56862745,
         0.54      ,  1.1509434 ,  1.66084034,  1.        ,  0.78723404],
       [ 0.69817998,  2.02080832,  1.58      ,  2.12      ,  0.56862745,
         1.54      ,  1.14296081,  1.10084034,  0.98979592,  0.78723404],
       [ 1.12371189,  1.99963004,  2.06862745,  1.68603774,  2.15353311,
         1.57692308,  2.16182874,  1.66633484,  1.51020408,  0.86258865],
       [ 1.75161887,  0.99963004,  2.06862745,  1.68603774,  2.15353311,
         1.57692308,  2.16182874,  1.66633484,  1.51020408,  0.86258865],
       [ 0.37209302,  1.49019608,  1.        ,  0.58      ,  1.07883153,
         0.5       ,  0.        ,  0.52941176

In [36]:
k_similar_item_profiles.shape

(5, 57)

In [37]:
index_user_matrix

array([[ 55.,  29.,  30.,   1.,  51.,  46.,  44.,   0.,   9.,  19.,  11.,
         47.,  25.,  42.,  52.,  50.,   1.,  47.,  52.,  21.,   9.,  20.,
         36.,  14.,   9.,   0.,  55.,  21.,  55.,  42.,  35.,  44.,  24.,
         39.,  56.,   8.,  29.,   5.,  25.,  55.,  20.,  34.,   7.,  53.,
         31.,  41.,  53.,  23.,  23.,   1.,  23.,  20.,  44.,  39.,  30.,
         39.,  35.],
       [ 53.,  49.,  44.,  35.,  56.,  37.,  48.,  35.,  35.,   4.,  28.,
         19.,  26.,  25.,  23.,  10.,   7.,  48.,  41.,  48.,  28.,  14.,
         41.,  10.,  56.,  35.,  12.,  52.,  47.,  25.,   0.,  19.,  25.,
         48.,  41.,   9.,  18.,  27.,  55.,  47.,  31.,  18.,  13.,  19.,
         30.,  13.,  44.,  33.,  33.,   8.,  55.,  35.,  41.,  10.,  47.,
         10.,  25.],
       [ 30.,  30.,   3.,  43.,  46.,  25.,  49.,  42.,  20.,   8.,  39.,
         30.,  51.,   1.,  21.,  23.,  37.,  35.,  36.,  55.,  39.,  10.,
         29.,  49.,   3.,  49.,   9.,  33.,  10.,   1.,  13.,  48.,  4

In [38]:
k_similar_item_similarity_values.shape

(5,)

In [39]:
cf3.type

'user'

In [29]:
import collaborative_filtering

In [30]:
cf5 = collaborative_filtering.collaborative_filtering(r"C:\Users\SHIVAM MAHAJAN\Desktop\Github\Recommendation-System\Data\Demo Data.xlsm"\
                                                      ,type = "item", algo = "knn")

In [31]:
cf5.similarity_matrix

[]

In [32]:
cf5.final_recommendation_score_matrix()

AttributeError: 'list' object has no attribute 'shape'

In [26]:
cf5.output_recommendations()

Customer_id  Merchant_id  Recommended_score  Rank  Flag
0            1.0          4.0           4.714821   1.0   0.0
1            1.0          9.0           4.225749   2.0   0.0
2            1.0         10.0           3.692240   3.0   0.0
3            1.0          7.0           3.180800   4.0   1.0
4            1.0          8.0           2.958557   5.0   1.0
5            1.0          5.0           2.865375   6.0   1.0
6            1.0          3.0           2.795271   7.0   1.0
7            1.0          2.0           2.743048   8.0   1.0
8            1.0          6.0           2.699288   9.0   1.0
9            1.0          1.0           2.122631  10.0   1.0
10           2.0          5.0           4.498337   1.0   0.0
11           2.0          9.0           4.206923   2.0   0.0
12           2.0         10.0           3.730359   3.0   0.0
13           2.0          7.0           3.166074   4.0   1.0
14           2.0          4.0           3.081859   5.0   1.0
15           2.0          8.0           2.967706   6.0   1.0
16           2.0          2.0           2.830833   7.0   1.0
17           2.0          3.0           2.804507   8.0   1.0
18           2.0          6.0           2.785059   9.0   1.0
19           2.0          1.0           2.161900  10.0   1.0
20           3.0          7.0           2.808965   1.0   0.0
21           3.0          8.0           2.786940   2.0   0.0
22           3.0          9.0           2.503744   3.0   0.0
23           3.0          6.0           2.501694   4.0   0.0
24           3.0         10.0           2.139184   5.0   0.0
25           3.0          1.0           1.980007   6.0   0.0
26           3.0          3.0           1.118044   7.0   1.0
27           3.0          4.0           1.061087   8.0   1.0
28           3.0          5.0           0.964065   9.0   1.0
29           3.0          2.0           0.958800  10.0   1.0
..           ...          ...                ...   ...   ...
540         55.0          7.0           4.097570   1.0   0.0
541         55.0          4.0           3.854523   2.0   0.0
542         55.0          9.0           3.491243   3.0   0.0
543         55.0          6.0           3.442827   4.0   0.0
544         55.0          3.0           2.127075   5.0   1.0
545         55.0          8.0           2.107831   6.0   1.0
546         55.0          5.0           2.038002   7.0   1.0
547         55.0          2.0           1.927440   8.0   1.0
548         55.0         10.0           1.564582   9.0   1.0
549         55.0          1.0           1.436377  10.0   1.0
550         56.0          4.0           5.245281   1.0   0.0
551         56.0          2.0           4.743731   2.0   0.0
552         56.0          7.0           3.825058   3.0   1.0
553         56.0          5.0           3.464327   4.0   1.0
554         56.0          8.0           3.462570   5.0   1.0
555         56.0          3.0           3.349303   6.0   1.0
556         56.0          9.0           3.288076   7.0   1.0
557         56.0          6.0           3.249387   8.0   1.0
558         56.0         10.0           2.840041   9.0   1.0
559         56.0          1.0           2.445535  10.0   1.0
560         57.0          3.0           4.067941   1.0   0.0
561         57.0          9.0           3.832037   2.0   0.0
562         57.0         10.0           3.218518   3.0   0.0
563         57.0          1.0           3.161900   4.0   0.0
564         57.0          7.0           2.608889   5.0   1.0
565         57.0          8.0           2.485973   6.0   1.0
566         57.0          4.0           2.479750   7.0   1.0
567         57.0          5.0           2.311771   8.0   1.0
568         57.0          6.0           2.303325   9.0   1.0
569         57.0          2.0           2.222090  10.0   1.0

[570 rows x 5 columns]